### ISSUE TITLE
Not working in IE11 ?

### ISSUE THREAD

**Issue by wake42** [seveves/angular-stencil#3]
Hi, I can't seem to get this to work in IE11 (It works in all other browsers I've tried: Chrome, Edge, Firefox, Safari & Opera). Is this by design or am I missing something?
I'm looking into building a framework agnostic component library in Stencil and getting it to work in IE11 is sadly a requirement.

The error I'm getting in IE11 is `SCRIPT5022: Exception thrown and not caught` in polyfills.bundle.js (859,36)

When I debug `iterFn` is undefined in that line:
`if (typeof iterFn != 'function') `

**Comment by seveves** [comment]
Hi @wake42 ... I've never tested this example in any browser other than Chrome.

Normally stenciljs provides the needed polyfills for web components by itself.
This repository also uses an older version of stenciljs. I should update this asap ...

But did you try to enable the polyfills located at [polyfills.ts](https://github.com/seveves/angular-stencil/blob/master/angular/src/polyfills.ts). Maybe we need one from there to make it work in IE11.

**Comment by seveves** [comment]
I've updated the repository to use the latest angular and stencil versions. Please pull the changes, install all updates with npm and test it again. It should work in IE11 now due to [these changes](https://github.com/seveves/angular-stencil/commit/c429d5ed2e791e31e2f3c9cfb451a5b0af985f39#diff-99f1a9f1ed8340f4404d243b893ce955)

**Comment by wake42** [comment]
Works like a charm now. I just have to figure out why my own project doesn't work...
Thanks for the update!
